+incdir+$UVM_HOME/src/
+incdir+../rtl/
../rtl/include/cv32e40p_pkg.sv
../rtl/cv32e40p_alu_div.sv
../rtl/cv32e40p_popcnt.sv
../rtl/cv32e40p_ff_one.sv
../rtl/cv32e40p_alu.sv
$UVM_HOME/src/uvm_pkg.sv
test_cfg.svh
alu_transaction.svh
alu_sequence.svh
alu_interface.v
alu_monitor.svh
alu_driver.svh
alu_seqr.svh
alu_agent.svh
alu_scbd.svh
alu_coverage.svh
alu_env.svh
alu_test.svh

